apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-moodle-operator-deployment
spec:
  inputs:
    resources:
    - type: git
      name: k8s-yamls-repo
  steps:
  - name: apply
    image: quay.io/openshift/origin-cli:latest
    workingdir: /workspace/k8s-yamls-repo
    command: ["/bin/bash", "-c"]
    args:
    - |-
      echo Applying manifests in directory
      oc apply -f moodle-operator/deploy/crds/*crd.yaml -n moodle
      oc apply -f moodle-operator/deploy/*.yaml -n moodle
      echo -----------------------------------