
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-moodle-operator
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
    - name: create-upate-deployment
      taskRef:
        name: apply-moodle-operator-deployment
      resources:
        inputs:
        - name: k8s-yamls-repo
          resource: source-repo