apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-deploy-moodle-operator-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy-moodle-operator
  resources:
  - name: source-repo
    resourceRef:
      name: moodle-operator-repo