apiVersion: moodle.netzlink.com/v1alpha1
kind: Moodle
metadata:
  name: example-moodle
spec:
  # Default values copied from <project_dir>/helm-charts/moodle/values.yaml
  
  affinity: {}
  allowEmptyPassword: true
  args: null
  certificates:
    args: null
    command: null
    customCAs: []
    customCertificate:
      certificateLocation: /etc/ssl/certs/ssl-cert-snakeoil.pem
      certificateSecret: ""
      chainLocation: /etc/ssl/certs/mychain.pem
      chainSecret: {}
      keyLocation: /etc/ssl/private/ssl-cert-snakeoil.key
    extraEnvVars: []
    extraEnvVarsCM: null
    extraEnvVarsSecret: null
    image:
      pullPolicy: IfNotPresent
      pullSecrets: []
      registry: docker.io
      repository: bitnami/minideb
      tag: buster
  command: null
  commonAnnotations: {}
  commonLabels: {}
  containerPorts:
    http: 8080
    https: 8443
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  customLivenessProbe: {}
  customReadinessProbe: {}
  existingSecret: null
  externalDatabase:
    database: bitnami_moodle
    host: ""
    password: ""
    port: 3306
    user: bn_moodle
  extraDeploy: []
  extraEnvVars: []
  extraEnvVarsCM: null
  extraEnvVarsSecret: null
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: null
  image:
    debug: false
    pullPolicy: IfNotPresent
    pullSecrets: null
    registry: docker.io
    repository: bitnami/moodle
    tag: 3.9.2-debian-10-r25
  ingress:
    annotations: {}
    certManager: false
    enabled: false
    hostname: moodle.local
    hosts: null
    secrets: null
    tls: null
  initContainers: []
  lifecycleHooks: null
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 600
    path: /login/index.php
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  mariadb:
    architecture: standalone
    auth:
      database: bitnami_moodle
      password: ""
      rootPassword: ""
      username: bn_moodle
    enabled: true
    primary:
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        existingClaim: null
        hostPath: null
        size: 8Gi
        storageClass: null
  metrics:
    enabled: false
    image:
      pullPolicy: IfNotPresent
      pullSecrets: null
      registry: docker.io
      repository: bitnami/apache-exporter
      tag: 0.8.0-debian-10-r177
    podAnnotations:
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
      prometheus.io/scrape: "true"
    service:
      annotations:
        prometheus.io/port: '{{ .Values.metrics.service.port }}'
        prometheus.io/scrape: "true"
      port: 9117
      type: LoadBalancer
  moodleEmail: user@example.com
  moodlePassword: ""
  moodleSkipInstall: false
  moodleUsername: user
  nameOverride: null
  nodeAffinityPreset:
    key: ""
    type: ""
    values: []
  nodeSelector: {}
  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    hostPath: null
    size: 8Gi
  podAffinityPreset: ""
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /login/index.php
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  replicaCount: 1
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
  service:
    externalTrafficPolicy: Cluster
    httpsPort: 443
    nodePorts:
      http: ""
      https: ""
    port: 80
    type: LoadBalancer
  sessionAffinity: None
  sidecars: []
  smtpHost: null
  smtpPassword: null
  smtpPort: null
  smtpProtocol: null
  smtpUser: null
  tolerations: []
  updateStrategy:
    type: RollingUpdate
  volumePermissions:
    enabled: false
    image:
      pullPolicy: Always
      pullSecrets: []
      registry: docker.io
      repository: bitnami/minideb
      tag: buster
    resources:
      limits: {}
      requests: {}
  
