apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: moodle-operator
  template:
    metadata:
      labels:
        name: moodle-operator
    spec:
      serviceAccountName: moodle-operator
      containers:
        - name: moodle-operator
          # Replace this with the built image name
          image: nicokahlert/moodle-operator:a3f6485f45e623158486f65aa07a5687a1960fcc
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "moodle-operator"
